name: FastAPI CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run FastAPI app
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Run tests and capture logs
        run: |
          pytest > result.log 2>&1 || true

      - name: Upload test logs as artifact
        uses: actions/upload-artifact@v2.3.1   # pinned to v2.3.1
        with:
          name: test-logs
          path: result.log
