name: FastAPI CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Using the latest Ubuntu for CI environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout code from the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # You can specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt  # Installing dependencies for FastAPI app

      - name: Run FastAPI app
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Wait for the server to start

      - name: Run tests
        run: |
          pytest  # Running pytest to test the FastAPI app
