name: FastAPI CI + Failure Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r app/requirements.txt httpx

      - name: Run FastAPI app
        run: |
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Run tests and capture logs
        id: run_tests
        run: |
          set +e
          pytest > result.log 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Upload logs for inspection
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: result.log

      - name: Notify on failure
        if: steps.run_tests.outputs.exit_code != '0'
        run: |
          echo "Tests failed—sending logs to webhook"
          PAYLOAD=$(
            jq -Rn --arg text "❌ FastAPI CI failed on $GITHUB_REPOSITORY@$GITHUB_REF" \
                  --arg logs "$(tail -n 200 result.log)" \
                  '{text: $text, logs: $logs}'
          )
          curl -X POST -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               https://webhook.site/1ab697f5-a8ec-4ce4-93ac-517b0768ea16
