name: Send failure logs via webhook

on:
  workflow_run:
    workflows: ["FastAPI CI Workflow"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download test logs artifact
        uses: actions/download-artifact@v3
        with:
          name: test-logs
          path: ./logs

      - name: Send logs to webhook.site
        run: |
          # Read last 200 lines to avoid huge payload
          LOGS=$(tail -n 200 ./logs/result.log | jq -Rs .)
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"text\": \"❌ FastAPI CI failed! Here are the last 200 lines of logs:\", \"logs\": $LOGS}" \
            https://webhook.site/1ab697f5-a8ec-4ce4-93ac-517b0768ea16
