name: Send failure logs via webhook

on:
  workflow_run:
    workflows: ["FastAPI CI Workflow"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Download test logs artifact
        uses: actions/download-artifact@v4
        with:
          name: test-logs
          path: ./logs

      - name: Send logs to webhook.site
        run: |
          # Tail the last 200 lines to keep payload reasonable
          LOGS=$(tail -n 200 ./logs/result.log | jq -Rs .)
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"text\": \"❌ FastAPI CI failed on $GITHUB_REPOSITORY#$GITHUB_REF. Last 200 log lines:\", \"logs\": $LOGS}" \
            https://webhook.site/1ab697f5-a8ec-4ce4-93ac-517b0768ea16
